client/urls.py
from django.urls import path
from . import views

app_name = "client"
urlpatterns = [
        path('<int:pk>/', views.index, name='index'), 
        path('<int:pk>/survey/', views.survey, name='survey'),
        path('<int:pk>/save/', views.save, name='save'),
        path('<int:pk>/feedback/', views.feedback, name='feedback')
]

takeSurvey/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ts.urls')),
    path('', include('client.urls')),
    path('admin/', admin.site.urls),
]

ts/urls.py
from django.urls import path
from . import views

app_name = 'ts'
urlpatterns = [
        path('', views.indexView.as_view(), name='index'), 
]

client/models.py
from django.db import models
from ts.models import Clients

class SurveyQuestion(models.Model):
    QTYPES = ((1, 'TEXT'), (2, 'CHOICE'))

    company_id = models.ForeignKey(Clients, on_delete=models.CASCADE)
    ques_id = models.AutoField(primary_key=True) 
    ques_category = models.CharField(default="GENERAL", max_length=255)
    ques_type = models.IntegerField(default=1, choices=QTYPES)
    ques_text = models.CharField(max_length=255)
    ques_meta_1 = models.CharField(max_length=255)
    ques_meta_2 = models.CharField(max_length=255)

    def __str__(self):
        return self.company_id.client_name + ": " + self.ques_text
        #return self.ques_text


class SurveyQuestionChoice(models.Model):
    company_id = models.ForeignKey(Clients, on_delete=models.CASCADE)
    ques_id = models.ForeignKey(SurveyQuestion, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)

    def __str__(self):
        return "(" + self.ques_id.ques_text + ") " + self.choice_text


class SurveyResponse(models.Model):
    company_id = models.ForeignKey(Clients, on_delete=models.CASCADE)
    ques_id = models.ForeignKey(SurveyQuestion, on_delete=models.CASCADE)
    user_response = models.CharField(max_length=255)

    def __str__(self):
        return self.user_response

ts/models.py
from django.db import models

class Clients(models.Model):
    company_id = models.AutoField(primary_key=True)
    client_name = models.CharField(max_length=100)
    survey_start_date = models.DateTimeField()
    status = models.IntegerField(default=1)

    class Meta:
        verbose_name_plural = "Clients"
    

    def __str__(self):
        return self.client_name

client/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.db.models import Count, Avg, Max, Min

from ts.models import *
from .models import SurveyQuestion, SurveyQuestionChoice, SurveyResponse

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

from fpdf import FPDF


class PDF(FPDF):
    def __init__(self, client_name):
        super().__init__()
        self.WIDTH = 210
        self.HEIGHT = 297
        self.name = client_name

    def header(self):
        self.image('ts/static/ts/index.png', 10, 3, 33)
        self.set_font('Arial', 'B', 11)
        self.cell(self.WIDTH - 80)
        self.cell(60, 1, self.name.upper() + ' SURVEY REPORT', 0, 0, 'R')
        self.ln(20)

    def footer(self): 
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, 'Page ' + str(self.page_no()), 0, 0, 'C')

    def page_body(self, images):
        self.image(images, 15, 35, self.WIDTH)

    def print_page(self, images): 
        self.add_page()
        self.page_body(images)


def index(request, pk):
    """
    This view is for
    creating dynamic
    and personalized
    client home page
    """

    ques_obj = SurveyQuestion.objects.filter(company_id=pk)
    res_obj = SurveyResponse.objects.filter(company_id=pk)

    total_survey_question = ques_obj.count()
    total_survey_response = res_obj.count()//total_survey_question

    stats_list = []
    charts = []
    for q in ques_obj:
        if q.ques_type == 1:
            res_obj = SurveyResponse.objects.filter(ques_id_id = q.ques_id)
            stat_dic =  res_obj.aggregate( \
                    Avg('user_response'), \
                    Max('user_response'), \
                    Min('user_response'))

            stat_dic['ques'] = q.ques_text
            stats_list.append(stat_dic)
        elif q.ques_type == 2: 
            choice_list = []
            res_list = []
            stats = []

            res_obj = SurveyResponse.objects.filter(ques_id_id = q.ques_id)
            choice_obj = SurveyQuestionChoice.objects.filter(ques_id_id = q.ques_id)

            choice_list = [c.choice_text for c in choice_obj]
            res_list = [r.user_response for r in res_obj]
            stats = [res_list.count(i) for i in set(res_list)]
            name = str(q.company_id_id) + '_' + str(q.ques_id)
 
            plt.pie(stats, labels=set(res_list), autopct='%1.0f%%')
            plt.title(q.ques_text)
            plt.legend()
            plt.savefig('client/static/client/charts/' + name + '.png', \
                    transparent=True)
            plt.close()
            charts.append(name)

    context = {
            'client': get_object_or_404(Clients, pk=pk),
            'total_ques': total_survey_question,  
            'total_response': total_survey_response, 
            'charts': charts,
            'stats': stats_list
    }

    pdf = PDF(context['client'].client_name)
    for i in charts:
        pdf.print_page('client/static/client/charts/' + i + '.png')

    pdf.output('client/static/client/' + str(pk) +'.pdf', 'F')

    return render(request, "client/index.html", context)


def survey(request, pk):
    """
    This view is for
    creating dynamic
    and personalized
    client survey page
    """

    context = {
            'client': get_object_or_404(Clients, pk=pk),
            'categories': SurveyQuestion.objects.filter(company_id=pk).values('ques_category').annotate(Count('ques_category')).order_by(),
            'ques_set': SurveyQuestion.objects.filter(company_id=pk),
            'choice_set': SurveyQuestionChoice.objects.filter(company_id=pk)
    } 

    return render(request, "client/survey.html", context)


def save(request, pk):
    """
    This view is for
    saving participant
    response into db
    """

    context = {
            'client': get_object_or_404(Clients, pk=pk)
    }

    for res in request.POST:
        if res == "csrfmiddlewaretoken" or res == "submit":
            continue

        response = SurveyResponse(
                company_id = Clients.objects.get(pk=pk), 
                ques_id = SurveyQuestion.objects.get(pk=int(res)), 
                user_response=request.POST[res]
        )

        response.save()

    return render(request, "client/thanks.html", context)


def feedback(request, pk):
    """
    This view is for
    saving participant
    feedback regarding
    survey
    """

    context = {'client': get_object_or_404(Clients, pk=pk)}
    return render(request, "client/feedback.html", context)

ts/views.py
from django.shortcuts import render
from django.views import generic
from .models import Clients

class indexView(generic.ListView):
    """
    Handle index page request.
    """

    template_name = 'ts/index.html'
    context_object_name = 'latest_survey_list'

    def get_queryset(self):
        return Clients.objects.all()

client/templates/client/feedback.html
{% extends "client/master.html" %}

{% block title %}FEEDBACK{% endblock %}

{% block main %}
<fieldset>
<legend>FEEDBACK FORM</legend>
<form action="{% url 'ts:index' %}" method="post">
{% csrf_token %}
<label for="emailid">Enter your email id: </label><br/>
<input type="text" id="emailid" name="emailid" placeholder="Your email id" autofocus required/>

<br/><br/>

<label for="name">Enter your full name: </label><br/>
<input type="text" id="name" name="name" placeholder="Your full name" required />

<br/><br/>

<label for="feed">Your Feedback</label><br/>
<textarea placeholder="Your feedback" width="80%" required></textarea>

<br/><br/>

<button type="submit">SUBMIT FEEDBACK</button>
</form>
</fieldset>
{% endblock %}

client/templates/client/index.html
{% extends "client/master.html" %}
{% load static %}

{% block title %} {{ client.client_name.upper }} SURVEY {% endblock %}

{% block main %}
<form action="{% url 'client:survey' client.company_id %}" method="post">
{% csrf_token %}
<label for="butSurvey"><strong>Please take this short survey. Thank you!</strong></label>
<button id="butSurvey" type="submit" autofocus>GO TO SURVEY!</button>
</form>

<div class="survey_index">
<fieldset>
<legend>SURVEY SUMMARY</legend>
<table>
<tr>
	<td>TOTAL NUMBER OF QUESTIONS</td>
	<td>{{ total_ques }}</td>
</tr>
<tr>
	<td>TOTAL NUMBER OF RESPONSES</td>
	<td>{{ total_response }}</td>
</tr>
</table>
<br/><br/>

<table>
<tr>
	<td><strong>QUESTION</strong></td>
	<td><strong>MAX</strong></td>
	<td><strong>MIN</strong></td>
	<td><strong>AVERAGE</strong></td>
</tr>
{% for s in stats %}
<tr>
	<td>{{ s.ques }}</td>
	<td>{{ s.user_response__max }}</td>
	<td>{{ s.user_response__min }}</td>
	<td>{{ s.user_response__avg }}</td>
</tr>
{% endfor %}
</table>

<br/><br/>
<a href="{% static 'client' %}/{{ client.company_id }}.pdf" target="_blank">
	<button>DOWNLOAD REPORT</button>
</a>
<br/><br/>

{% for i in charts %}
<img src="{% static 'client/charts/' %}{{ i }}.png" />
{% endfor %}

</fieldset>

<br/><br/>

<a href="{% url 'ts:index' %}">Go to home</a>
</div>
{% endblock %}

client/templates/client/master.html
{% load static %}

<!DOCTYPE html>

<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" type="image/png" href="{% static 'ts/index.png' %}" />
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% static 'client/style.css' %}">
</head>

<body>
<header>
<h1>{{ client.client_name.upper }}</h1>
</header>

<main>
	{% block main %}{% endblock %}
</main>
</body>
</html>

client/templates/client/survey.html
{% extends "client/master.html" %}

{% block title %} {{ client.client_name.upper }} SURVEY {% endblock %}

{% block main %}
<div class="container-fluid">
<div class="container">
<form action="{% url 'client:save' client.company_id %}" method="POST">
{% csrf_token %}

{% for category in categories %}
<fieldset>
<legend>{{ category.ques_category }}</legend>

{% for q in ques_set %}
{% if q.ques_category == category.ques_category %}

{% if q.ques_type == 1 %}
<input type="text" placeholder="{{ q.ques_text }}" id="{{ q.ques_id }}" name="{{ q.ques_id }}" min="{{ q.ques_meta_1 }}" max="{{ q.ques_meta_2 }}" required /><br/>

{% elif q.ques_type == 2 %}
<label for="{{ q.ques_id }}">{{ q.ques_text }}</label><br/>

{% for c in choice_set %}
{% if c.ques_id.ques_id == q.ques_id %}
<input type="radio" name="{{ q.ques_id }}" id="{{ q.ques_id }}_{{ forloop.counter }}" value="{{ c.choice_text }}" required />
<label for="{{ q.ques_id }}_{{ forloop.counter }}">{{ c.choice_text }}</label>
{% endif %}
{% endfor %}
<br/>
{% endif%}
{% endif %}
{% endfor %}
</fieldset>
{% endfor %}

<br/><br/>

<a href="{% url 'client:index' client.company_id %}">
<button type="button" id="back" name="back">BACK</button>
</a>
<button type="reset" id="reset" name="reset">RESET</button>
<button type="submit" id="submit" name="submit">SUBMIT</button>
</form>
</div>
</div>

{% endblock %}

client/templates/client/thanks.html
{% extends "client/master.html" %}

{% block title %} THANK YOU {% endblock %}

{% block main %}
<h1>THANKS FOR TAKING THIS SURVEY.</h1>

<form action="{% url 'client:index' client.company_id %}" method="POST">
{% csrf_token  %}
<button type="submit">GO TO SUMMARY PAGE</button>
</form>

<a href="{% url 'ts:index' %}">Go to home</a>
<a href="{% url 'client:feedback' client.company_id %}">Give feedback</a>

{% endblock %}

ts/templates/ts/index.html
{% extends "ts/master.html" %}

{% block title %} We Take Survery {% endblock %}

{% block main %}
<ul>
{% for survey in latest_survey_list %}
	<li><a href="{{ survey.company_id }}/">{{ survey.client_name.upper }}</a></li>
{% empty %}
	<p class="error">NO SURVEY AVAILABLE.</p>
{% endfor %}
</ul>
{% endblock %}

ts/templates/ts/master.html
{% load static %}

<!doctype html>

<html lang="eng">

<head>
<meta charset="UTF-8">
<link rel="shortcut icon" type="image/png" href="{% static 'ts/index.png'%}" />
<title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="{% static 'ts/style.css' %}">
</head>

<body>

<div class="sidebar">
<div class="sidebar-brand">
	<h1>takeSurvey<span>.com</span></h1>
</div>

<div class="sidebar-items">
</div>
</div>

<header>	
	<h1>DASHBOARD</h1>
	<a href="admin/"><button>ADMIN LOG IN</button></a>
</header>

<main>
<h3>RECENT SURVEYS</h3>
{% block main %}{% endblock %}
</main>

<aside>
<h3>ABOUT US</h3>
<address>
<strong>'takeSurvey.com'</strong> conduct survey(s) on behalf of their clients, mostly PRODUCT based companies. We are recognised by many big firms and are known for our quality surveys. Our firm was established in year <time>2020</time> by Mr. <strong>ADITYA JAIN</strong>.
</address>
<br/>

<h3>POST US</h3>
<address>P-33/2 Industrial Area, Delhi-110020</address>
<br/>

<h3>WRITE US</h3>
<address>info@takesurvey.com</address>
<br/>

<h3>FOLLOW US</h3>
<a href="#"><img src="{% static 'ts/instagram.png'%}" width="50" height="50"></a>
<a href="#"><img src="{% static 'ts/facebook.png'%}" width="50" height="50"></a>
<a href="#"><img src="{% static 'ts/twitter.png'%}" width="50" height="50"></a>
</aside>
</body>

<footer>
<a href="">Terms</a>
<a href="">Privacy Policy</a>
</footer>

</html>